version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_weather
    restart: on-failure
    ports:
      - "5432:5432"