version: '3.8'

services:
  ai-weather:
    image: ${TXY_REGISTRY}/${TXY_PROJECT}/ai-weather:latest
    platform: linux/amd64
    pull_policy: always
    container_name: ai-weather
    ports:
      - "8081:8081"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      DB_HOST: ai-pg
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schema=public
      PORT: 8081
      TZ: Asia/Shanghai
    restart: on-failure
    depends_on:
      - ai-pg
    networks:
      - ai-network
      - data-harvester-network  # 加入 data-harvester 的网络

  ai-pg:
    image: postgres:17.4
    container_name: ai-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_weather
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
  data-harvester-network:
    external: true  # 这个网络已存在，不要新建
    name: data-harvester_data-harvester-network

volumes:
  postgres_data:
